packages:
  # apps directory
  - 'apps/*'
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # graphql related packages
  - 'packages/graphql/*'

catalog:
  "@nestjs/axios": "^4.0.1"
  "@nestjs/common": "^11.0.1"
  "@nestjs/config": "^4.0.2"
  "@nestjs/core": "^11.0.1"
  "@nestjs/graphql": "^13.2.3"
  "@nestjs/apollo": "^13.2.3"
  "@nestjs/platform-express": "^11.0.1"
  "@nestjs/cli": "^11.0.0"
  "@nestjs/schematics": "^11.0.0"
  "@nestjs/testing": "^11.0.1"
  "@apollo/subgraph": "^2.12.2"
  "@apollo/server": "^5.2.0"
  "@apollo/gateway": "^2.12.2"
  "graphql": "^16.12.0"
  "nestjs-pino": "^4.5.0"
  "pino-http": "^11.0.0"
  "pino-pretty": "^13.1.3"
  "reflect-metadata": "^0.2.2"
  "rxjs": "^7.8.1"
  "@types/express": "^5.0.0"
  "@types/jest": "^30.0.0"
  "@types/node": "^22.10.7"
  "@types/supertest": "^6.0.2"
  "jest": "^30.0.0"
  "lint-staged": "^16.2.7"
  "prettier": "^3.4.2"
  "source-map-support": "^0.5.21"
  "supertest": "^7.0.0"
  "ts-jest": "^29.2.5"
  "ts-loader": "^9.5.2"
  "ts-node": "^10.9.2"
  "tsc-alias": "^1.8.16"
  "tsconfig-paths": "^4.2.0"
  "typescript": "5.9.3"