name: Change detection
author: yuriihorchuk
description: This reusable action for tracking changes of packages and apps
runs:
  using: 'composite'
  steps:
    - name: change detection
      id: set-matrix
      shell: bash
      run: |
        CHANGES=$(npx turbo ls --filter='...[origin/main]' --targets='build' --json | jq -c '.packages | map(select(.path | startswith("apps/"))) | map(.name)')
        if [ "$CHANGES" == "[]" ]; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
           echo "matrix=$CHANGES" >> $GITHUB_OUTPUT
        fi